news/urls.py
from django.urls import path
from .views import ArticleDetailView, ArticleListView

app_name = "news"

urlpatterns = [
    path('', ArticleListView.as_view(), name="article-list"),
    path('<int:pk>', ArticleDetailView.as_view(), name="article-detail"),
]

news_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('news/', include('news.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Editor(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name
    

class Contributor(models.Model):
    name = models.CharField(max_length=100)
    editor = models.ForeignKey(Editor, null=True, blank=True, on_delete=models.SET_NULL)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Article(models.Model):
    column_name = models.CharField(max_length=200)
    headline = models.CharField(max_length=200)
    subheadline = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    contributor = models.ForeignKey(Contributor, null=True, blank=True, on_delete=models.PROTECT)
    image = models.ImageField(null=True, blank=True, upload_to="article_images/")
    content = models.TextField()
    editor = models.ForeignKey(Editor, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.headline
    

news/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views import generic
from typing import Any

from .models import Article


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'news/article_list.html', {'articles': articles})


def article_detail(request, article_id):
    article = Article.objects.get(id=article_id)
    return render(request, 'news/article_detail.html', {'article': article})

class ArticleListView(generic.ListView):
    model = Article
    # paginate_by = 1
    context_object_name = "articles"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context
    
    def get_queryset(self):
        user = self.request.user
        queryset = Article.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:3]
        return queryset


class ArticleDetailView(generic.DetailView):
    model = Article
    context_object_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        
        return context

news/templates/news/article_detail.html
{% extends 'base.html' %}
<h1>{{ article.title }}</h1>
<p>{{ article.content }}</p>


{% block content %}
<section class="max-w-3xl mx-auto text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-12">
        <div class="ml-5">
          <a href="{% url 'news:article-list' %}">
            <button type="button" class="ml-5 w-full flex items-center justify-center w-1/2 px-5 py-2 text-sm text-gray-700 transition-colors duration-200 bg-white border rounded-lg gap-x-2 sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-gray-200 dark:border-gray-700">
              <svg class="w-5 h-5 rtl:rotate-180" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18" />
              </svg>
              <span>Go back</span>
            </button>
          </a>
        </div>

        <div class="p-12 md:w-full flex flex-col items-start">
          <span class="inline-block py-1 px-2 rounded bg-pink-50 text-pink-500 text-xs font-medium tracking-widest">{{ article.category}}</span>
          <h2 class="sm:text-3xl text-2xl title-font font-medium text-gray-900 mt-4 mb-4">{{ article.headline }}</h2>
          <div class="border-b-2 md:w-full">
            <a class="inline-flex items-center">
                <img alt="blog" src="https://dummyimage.com/104x104" class="w-12 h-12 rounded-full flex-shrink-0 object-cover object-center">
                <span class="flex-grow flex flex-col pl-4">
                <span class="title-font font-medium text-gray-900">{{ article.contributor }}</span>
                <span class="text-gray-400 text-xs tracking-widest mt-0.5">Editor: {{ article.editor }}</span>
                </span>
            </a>
            <br>
            <br>
        </div>
        <br>

          <p class="leading-relaxed mb-8">{{ article.content }}</p>
          <div class="flex items-center flex-wrap pb-4 mb-4 border-b-2 border-gray-100 mt-auto w-full">
            <a class="text-pink-500 inline-flex items-center">More Stories</a>
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
            <span class="text-gray-400 mr-3 inline-flex items-center ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
              <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                <circle cx="12" cy="12" r="3"></circle>
              </svg>1.2K
            </span>
            <span class="text-gray-400 inline-flex items-center leading-none text-sm">
              <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
              </svg>6
            </span>
          </div>
        </div>
        
      </div>
    </div>
  </section>

{% endblock content %}

news/templates/news/article_list.html
{% extends 'index.html' %}

{% block topsection %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    {% for article in articles %}
    <div class="my-4 bg-white divide-y-2 divide-gray-100">
      <div class="border mb-2 py-8 flex flex-wrap md:flex-nowrap">
        <div class="py-2 px-2 md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-gray-700">{{ article.category }}</span>
          <span class="mt-1 text-gray-500 text-sm">{{ article.pub_date }}</span>
          <div class="sample-image w-40 mt-2">
            <img src="{{ article.image.url }}">
          </div>
        </div>
        <div class="md:flex-grow">
          <h2 class="text-2xl font-medium text-gray-900 title-font mb-2"><a href="{{ article.id }}">{{ article }} </li>
              </a></h2>
          <p class="leading-relaxed">{{ article.subheadline }}</p>
          <a class="text-pink-500 inline-flex items-center mt-4" href="{% url 'news:article-detail' article.id %}">Read
            article
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock topsection %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loiters' Collective</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .logo {
            width: 250px;
        }

        .top-of-page {
            min-height: 600px;
        }

        .photo-section {
            height: 400px;
        }
    </style>
</head>

<body>
    {% load static %}
    <div>
        {% include "navbar.html" %}
        <main class="bg-slate-300 mb-auto px-12 py-12">
            {% block content %}
            {% endblock content %}
        </main>

        <footer class="bg-white rounded-lg shadow m-4 dark:bg-gray-800 h-52">
            <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
                <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a
                        href="https://flowbite.com/" class="hover:underline">Loiterers' Collective™</a>. All Rights
                    Reserved.
                </span>
                <ul
                    class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
                    <li>
                        <a href="#" class="hover:underline me-4 md:me-6">About</a>
                    </li>
                    <li>
                        <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
                    </li>
                    <li>
                        <a href="#" class="hover:underline">Contact</a>
                    </li>
                </ul>
            </div>
        </footer>
    </div>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="top-of-page bg-blue-200 grid grid-cols-12 gap-4">
    <div class="left-side-section col-start-1 col-end-3 bg-yellow-200">
        Business
    </div>
    <div class="main-section bg-yellow-900 col-start-3 col-end-10">
        {% block topsection %}
        {% endblock topsection %}
    </div>
    <div class="right-side-section bg-yellow-400 col-start-10 col-end-13">
        Opinions
    </div>
</div>
<section class="photo-section bg-blue-800">
    <div class="focus"></div>
    <div class="photo-list">
        <ul>
            <li>photos</li>
        </ul>
    </div>
</section>
<div class="divider-container bg-blue-500">
    <div class="topic">
        World
    </div>
    <ul class="list-container">
        <li>
            <div class="photo">

            </div>
            <div class="some-headline">

            </div>
        </li>
    </ul>
</div>
{% endblock content %}

templates/navbar.html
{% load static %}

<header class="text-white bg-blue-950 body-font">
    <div class="bg-blue-950 container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <div class="logo_container ">
        <a href="/news" class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
          <span>
            <img src="{% static 'images/logo-2.png' %}" class="logo">
          </span>
        </a>
      </div>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a class="mr-5 hover:text-white" href="">extra</a>
        <a class="mr-5 hover:text-white" href="">World</a>
        <a class="mr-5 hover:text-white" href="">India</a>
        <a class="mr-5 hover:text-white" href="">Business</a>
        <a class="mr-5 hover:text-white" href="">Technology</a>
        <a class="mr-5 hover:text-white" href="">Sports</a>
        <a class="mr-5 hover:text-white" href="">More</a>
        <button class="ml-2 items-center bg-green-400 border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 rounded text-base mt-4 md:mt-0">
          Sign Up
          <!-- <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg> -->
        </button>
        <button class="ml-2 inline-flex items-center bg-red-400 border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 rounded text-base mt-4 md:mt-0">
          Log In
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>
    </div>
    <hr>
    <div class="Search m-2" style="display: flex; justify-content: right;">
        <div class="search-box">
            <textarea placeholder="Search" class="h-8 p-1"></textarea>
        </div>
    </div>
    <hr />
  </header>